MagnificoPonto/MagnificoPonto/Controllers/AmigurumiController.cs
using MagnificoPonto.Models;
using MagnificoPonto.Repositories.Interfaces;
using MagnificoPonto.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace MagnificoPonto.Controllers
{
    public class AmigurumiController : Controller
    {
        private readonly IAmigurumiRepository _amigurumiRepository;

        public AmigurumiController(IAmigurumiRepository amigurumiRepository)
        {
            _amigurumiRepository = amigurumiRepository;
        }

        public IActionResult List(string categoria)
        {
            IEnumerable<Amigurumi> amigurumis;
            string categoriaAtual = string.Empty;

            if(string.IsNullOrEmpty(categoria))
            {
                amigurumis = _amigurumiRepository.Amigurumis.OrderBy(a => a.AmigurumiId);
                categoriaAtual = "Todos os Amigurumis";
            }
            else
            {
                amigurumis = _amigurumiRepository.Amigurumis
                    .Where(a => a.Categoria.CategoriaNome.Equals(categoria))
                    .OrderBy(c => c.Nome);

                categoriaAtual = categoria;
            }

            var amigurumisListViewModel = new AmigurumiListViewModel
            {
                Amigurumis = amigurumis,
                CategoriaAtual = categoriaAtual
            };

            return View(amigurumisListViewModel);
        }

        public IActionResult Details (int amigurumiId)
        {
            var amigurumi = _amigurumiRepository.Amigurumis.FirstOrDefault(a=> a.AmigurumiId == amigurumiId);

            return View(amigurumi);
        }

        public ViewResult Search(string searchString)
        {
            IEnumerable<Amigurumi> amigurumis;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(searchString))
            {
                amigurumis = _amigurumiRepository.Amigurumis.OrderBy(p => p.AmigurumiId);
                categoriaAtual = "Todos os Amigurumis";
            }
            else
            {
                amigurumis = _amigurumiRepository.Amigurumis
                             .Where(p => p.Nome.ToLower().Contains(searchString.ToLower()));

                if (amigurumis.Any())

                    categoriaAtual = "Amigurumis";

                else

                    categoriaAtual = "Nenhum Amigurumi foi encontrado";
            }

            return View("~/Views/Amigurumi/List.cshtml", new AmigurumiListViewModel
            {
                Amigurumis = amigurumis,
                CategoriaAtual = categoriaAtual
            });
        }
    }
}

MagnificoPonto/MagnificoPonto/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace MagnificoPonto.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MagnificoPonto/MagnificoPonto/Views/Shared/_AmigurumisResumo.cshtml
@model Amigurumi

<div class="col-sm-4 col-md-4 col-lg-4">
    <p> <img src="@Model.ImagemUrl" class="img-fluid"></p>
    <h3>Preço : @Model.Preco.ToString("c")</h3>

    <h4>
        <a asp-controller="Amigurumi" asp-action="Details" asp-route-amigurumiId="@Model.AmigurumiId">@Model.Nome</a>
    </h4>

    <p>@Model.Descricao</p> @* mudar para personalização *@

    <div>
        <p class="button">
            <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-AmigurumiId="@Model.AmigurumiId">Incluir no Carrinho</a>

        </p>
    </div>

</div>

MagnificoPonto/MagnificoPonto/Views/Shared/_Carousel.cshtml
<div id="carouselMagnificoPonto" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/elefante.jpg" width="500" height="500" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/images/emilia.jpg" width="500" height="500" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/images/pato.jpg" width="500" height="500" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselMagnificoPonto" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselMagnificoPonto" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

MagnificoPonto/MagnificoPonto/Views/Shared/_Footer.cshtml
<footer>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
        <div class="container">
            <div class="row">

                <div class="col-10 col-md-5 col-lg-5 offset-1" style="color: white">
                    <h4> &copy; 2024 - Magnifico Ponto</h4>
                    <p class="text-justify">
                        Texto propaganda
                    </p>
                </div>

                <div class="col-10 col-md-5 col-lg-5 offset-1" style="color: white">
                    <h4> Tem alguma dúvida?</h4>
                    <ul class="list-unstyled">
                        <li class="py-1"> Endereço</li>
                        <li class="py-1"> Telefone</li>
                        <li class="py-1"> <a href="email@email.com" style="color: yellow">magnificoponto email</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</footer>

MagnificoPonto/MagnificoPonto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MagnificoPonto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MagnificoPonto.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="adicionar logo" />
                    Magnifico Ponto
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @await Component.InvokeAsync("CarrinhoCompraResumo")
                    @await Component.InvokeAsync("CategoriaMenu")
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    @* <a class="nav-link text-light" asp-area="" asp-controller="Amigurumi" asp-action="List">Amigurumis</a> *@
                    <a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                    <form class="navbar-form navbar-right" asp-controller="Amigurumi" asp-action="Search" method="get">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Procurar Amigurumi" name="searchString" value="@ViewData["searchString"]" />
                        </div>
                    </form>
                    @await Html.PartialAsync("_LoginPartial")
                    @if (User.IsInRole("Admin"))
                    {
                        <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Magnífico Ponto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@

    <partial name="_Footer"/>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>