codigo-fonte/MagnificoPonto/MagnificoPonto/Controllers/FormularioEntregasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MagnificoPonto.Data;
using MagnificoPonto.Models;

namespace MagnificoPonto.Controllers
{
    public class FormularioEntregasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FormularioEntregasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: FormularioEntregas
        public async Task<IActionResult> Entregas()
        {
              return View(await _context.FormularioEntregas.ToListAsync());
        }

        /*
        // GET: FormularioEntregas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.FormularioEntregas == null)
            {
                return NotFound();
            }

            var formularioEntrega = await _context.FormularioEntregas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (formularioEntrega == null)
            {
                return NotFound();
            }

            return View(formularioEntrega);
        }
        */

        // GET: FormularioEntregas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FormularioEntregas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Email,Telefone,Rua,Numero,Bairro,Cep,Referencia,Criacao")] FormularioEntrega formularioEntrega)
        {
            if (ModelState.IsValid)
            {
                _context.Add(formularioEntrega);
                await _context.SaveChangesAsync();
                HttpContext.Session.SetInt32("FormularioEntregaId", formularioEntrega.Id);
                return RedirectToAction("Index", "ShoppingCart");  //return RedirectToAction(nameof(Create));
            }
            return View(formularioEntrega);
        }

        /*

        // GET: FormularioEntregas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.FormularioEntregas == null)
            {
                return NotFound();
            }

            var formularioEntrega = await _context.FormularioEntregas.FindAsync(id);
            if (formularioEntrega == null)
            {
                return NotFound();
            }
            return View(formularioEntrega);
        }

        // POST: FormularioEntregas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Email,Telefone,Rua,Numero,Bairro,Cep,Referencia,Criacao")] FormularioEntrega formularioEntrega)
        {
            if (id != formularioEntrega.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(formularioEntrega);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FormularioEntregaExists(formularioEntrega.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(formularioEntrega);
        }

        // GET: FormularioEntregas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.FormularioEntregas == null)
            {
                return NotFound();
            }

            var formularioEntrega = await _context.FormularioEntregas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (formularioEntrega == null)
            {
                return NotFound();
            }

            return View(formularioEntrega);
        }

        // POST: FormularioEntregas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.FormularioEntregas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.FormularioEntregas'  is null.");
            }
            var formularioEntrega = await _context.FormularioEntregas.FindAsync(id);
            if (formularioEntrega != null)
            {
                _context.FormularioEntregas.Remove(formularioEntrega);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FormularioEntregaExists(int id)
        {
          return _context.FormularioEntregas.Any(e => e.Id == id);
        }
        */
    }
}

codigo-fonte/MagnificoPonto/MagnificoPonto/Controllers/ShoppingCartController.cs
using MagnificoPonto.Data;
using MagnificoPonto.Models;
using MagnificoPonto.Services.Models;
using MagnificoPonto.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace MagnificoPonto.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShoppingCartController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ShoppingCart
        public async Task<IActionResult> Index()
        {
            var shoppingCartId = HttpContext.Session.GetInt32("ShoppingCartId");

            if (shoppingCartId == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.ShoppingCarts
                .Include(s => s.CartItems)
                .ThenInclude(c => c.Product)
                .FirstOrDefaultAsync(s => s.ShoppingCartId == shoppingCartId);

            if (shoppingCart == null)
            {
                return NotFound();
            }

            if (HttpContext.Session.GetInt32("FormularioEntregaId") != null){
                var formularioEntrega = await _context.FormularioEntregas.FirstOrDefaultAsync(s => s.Id == HttpContext.Session.GetInt32("FormularioEntregaId"));
                List<int> productIds = shoppingCart.CartItems.Select(c => c.Product.Id).ToList();

                List<ProdutoModel> models = await _context.Produtos
                    .Where(m => productIds.Contains(m.Id))
                    .ToListAsync();

                if (!models.Any())
                {
                    NotFound();
                }

                var result = await MelhorEnvioService.GetApiResponse(models, formularioEntrega.Cep.ToString());
                List<MelhorEnvioResponse> rootList = JsonConvert.DeserializeObject<List<MelhorEnvioResponse>>(result.Content);
                List<Dictionary<string, string>> keyValuePairs = new List<Dictionary<string, string>>();
                foreach (var item in rootList)
                {
                    var dict = new Dictionary<string, string>
                    {
                        { "Serviço", item.name },
                        { "Preço", item.price != null ? item.price : "" }
                    };
                    keyValuePairs.Add(dict);
                }

                ViewBag.Result = keyValuePairs;
            }
            
            return View(shoppingCart);
        }

        // POST: ShoppingCart/AddToCart/5
        [HttpPost]
        public async Task<IActionResult> AddToCart(int productId, string description)
        {
            var shoppingCartId = HttpContext.Session.GetInt32("ShoppingCartId");
            
            var product = await _context.Produtos.FindAsync(productId);
            if (product == null)
            {
                return NotFound();
            }

            var cartItem = new CartItem { Product = product, Quantity = 1, Description = description };
            ShoppingCart shoppingCart;
            if (shoppingCartId == null) 
            { 
                shoppingCart = new ShoppingCart(); 
                shoppingCart.CartItems = new List<CartItem>
                    {
                        cartItem
                    };
                _context.Add(shoppingCart);
            }
            else
            {
                shoppingCart = await _context.ShoppingCarts
                .Include(s => s.CartItems)
                .ThenInclude(c => c.Product)
                .FirstOrDefaultAsync(s => s.ShoppingCartId == shoppingCartId);

                cartItem.ShoppingCart = shoppingCart;
                _context.Add(cartItem);
            }

            
            await _context.SaveChangesAsync();

            HttpContext.Session.SetInt32("ShoppingCartId", shoppingCart.ShoppingCartId);

            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int cartItemId)
        {
            var shoppingCartId = HttpContext.Session.GetInt32("ShoppingCartId");

            var shoppingCart = await _context.ShoppingCarts.Include(s => s.CartItems).FirstOrDefaultAsync(s => s.ShoppingCartId == shoppingCartId);

            if (shoppingCart == null)
            {
                return NotFound();
            }

            var cartItem = shoppingCart.CartItems.Find(s => s.CartItemId == cartItemId);

            shoppingCart.CartItems.Remove(cartItem);

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

codigo-fonte/MagnificoPonto/MagnificoPonto/Controllers/VendaProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MagnificoPonto.Data;
using MagnificoPonto.Models;
using MagnificoPonto.Services.Models;
using MagnificoPonto.Services;
using Newtonsoft.Json;

namespace MagnificoPonto.Controllers
{
    public class VendaProdutosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VendaProdutosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: VendaProdutos
        public async Task<IActionResult> Index()
        {
            return View(await _context.VendaProdutos.ToListAsync());
        }

        // GET: VendaProdutos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.VendaProdutos == null)
            {
                return NotFound();
            }

            var vendaProdutosModel = await _context.VendaProdutos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vendaProdutosModel == null)
            {
                return NotFound();
            }

            return View(vendaProdutosModel);
        }

        // GET: VendaProdutos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VendaProdutos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Preco,Cor,Tamanho,Quantidade,Personalizacao,CriadoEm")] VendaProdutosModel vendaProdutosModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vendaProdutosModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vendaProdutosModel);
        }

        // GET: VendaProdutos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.VendaProdutos == null)
            {
                return NotFound();
            }

            var vendaProdutosModel = await _context.VendaProdutos.FindAsync(id);
            if (vendaProdutosModel == null)
            {
                return NotFound();
            }
            return View(vendaProdutosModel);
        }

        // POST: VendaProdutos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Preco,Cor,Tamanho,Quantidade,Personalizacao,CriadoEm")] VendaProdutosModel vendaProdutosModel)
        {
            if (id != vendaProdutosModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vendaProdutosModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendaProdutosModelExists(vendaProdutosModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Edit));  //return RedirectToAction(nameof(Index));
            }
            return View(vendaProdutosModel);
        }

        // GET: VendaProdutos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.VendaProdutos == null)
            {
                return NotFound();
            }

            var vendaProdutosModel = await _context.VendaProdutos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vendaProdutosModel == null)
            {
                return NotFound();
            }

            return View(vendaProdutosModel);
        }

        // POST: VendaProdutos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.VendaProdutos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.VendaProdutos'  is null.");
            }
            var vendaProdutosModel = await _context.VendaProdutos.FindAsync(id);
            if (vendaProdutosModel != null)
            {
                _context.VendaProdutos.Remove(vendaProdutosModel);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VendaProdutosModelExists(int id)
        {
            return _context.VendaProdutos.Any(e => e.Id == id);
        }

        // Listagem de Produtos

        public async Task<IActionResult> ListaProdutos()
        {
            var listarProdutos = await _context.Produtos.ToListAsync();
            return View(listarProdutos);
        }

        // GET: Produtos/Details/5
        public async Task<IActionResult> InfoProdutos(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produtoModel = await _context.Produtos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produtoModel == null)
            {
                return NotFound();
            }

            return View(produtoModel);
        }
    }
}

codigo-fonte/MagnificoPonto/MagnificoPonto/Views/ShoppingCart/Index.cshtml
@model MagnificoPonto.Models.ShoppingCart

<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>Magnífico Ponto - Produtos</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;700;900&display=swap" rel="stylesheet">

    <link href="~/front/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/front/css/bootstrap-icons.css" rel="stylesheet">

    <link rel="stylesheet" href="~/front/css/slick.css" />

    <link href="~/front/css/magnifico-ponto.css" rel="stylesheet">
</head>

<body>
    <main>
        <div><span><br /><br /><br /><br /></span></div>

        <table class="table">
            <thead>
                <tr class="text-center align-middle">
                    <th>Amigurumi</th>
                    <th>Nome do produto</th>
                    <th>Quantidade</th>
                    <th>Preço</th>
                    <th>Total</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody class="text-center align-middle">
                @{
                    decimal total = 0;
                    if (Model.CartItems != null)
                    {
                        foreach (var cartItem in Model.CartItems)
                        {
                            <tr>
                                <td><img src="~/Amigurumis/@(cartItem.Product.ImageFileName)" width="100" /></td>
                                <td>@cartItem.Product.Nome</td>
                                <td>@cartItem.Quantity</td>
                                <td>@cartItem.Product.Preco</td>
                                <td>@(cartItem.Quantity * cartItem.Product.Preco)</td>
                                <td>
                                    <form asp-action="Delete" method="post">
                                        <button type="submit" class="btn btn-danger">Remover Item</button>
                                        <input type="hidden" id="cartItemId" name="cartItemId" value="@cartItem.CartItemId" />
                                    </form>
                                </td>
                            </tr>
                            total += cartItem.Quantity * cartItem.Product.Preco;
                        }
                    }
                }
            </tbody>
        </table>


        <form method="post" action="Payment/CreateCheckoutSession">
            <div class="text-end">
                <label for="name">Total:</label>
                <p id="total">@total</p>
                <input type="hidden" id="amount" name="amount" value="@total" />
                <input type="hidden" id="shoppingCartId" name="shoppingCartId" value="@Model.ShoppingCartId" />
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div>
                        <a class="btn btn-primary btn-lg rounded-pill mt-3" asp-controller="VendaProdutos" asp-action="ListaProdutos">Continuar comprando</a>
                    </div>

                    <div>
                        <a class="btn btn-success btn-lg rounded-pill mt-3" asp-controller="FormularioEntregas" asp-action="Create">Inserir dados para entrega</a>
                    </div>
                </div>

                <div class="col-md-6">
                    @if (ViewBag.Result != null)
                    {
                        <div>
                            @if (ViewBag.Result != null)
                            {
                                
                                    <table>
                                        <thead>
                                            <tr>
                                                <th>Select</th>
                                                <th>Serviço</th>
                                                <th>Preço</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var pair in ViewBag.Result)
                                            {
                                                <tr>
                                                    <td><input type="radio" name="service" value="@pair["Preço"]" /></td>
                                                    <td>@pair["Serviço"]</td>
                                                    <td>@pair["Preço"]</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                
                            }
                        </div>
                    }
                </div>
            </div>

            

            <button class="btn custom-btn cart-btn rounded-pill mt-3" type="submit">Finalizar pedido</button>
        </form>        


    </main>

    <script>
        var radios = document.getElementsByName('service');

        var baseValueElement = document.getElementById('total');
        var baseValue = parseFloat(baseValueElement.innerText);

        var amountInput = document.getElementById('amount');

        var previousOptionValue = 0;

        for (var i = 0; i < radios.length; i++) {
            radios[i].addEventListener('change', function () {
                var optionValue = parseFloat(this.value);

                if (isNaN(optionValue)) {
                    console.error('Invalid option value:', this.value);
                    return;
                }

                var total = baseValue - previousOptionValue + optionValue;

                baseValueElement.innerText = total.toFixed(2);

                amountInput.value = total.toFixed(2);

                previousOptionValue = optionValue;

                baseValue = total;
            });
        }
    </script>
   

    <!-- JAVASCRIPT FILES -->
    <script src="~/front/js/jquery.min.js"></script>
    <script src="~/front/js/bootstrap.bundle.min.js"></script>
    <script src="~/front/js/Headroom.js"></script>
    <script src="~/front/js/jQuery.headroom.js"></script>
    <script src="~/front/js/slick.min.js"></script>
    <script src="~/front/js/custom.js"></script>

</body>

</html>