codigo-fonte/MagnificoPonto/MagnificoPonto/Controllers/ContatosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MagnificoPonto.Data;
using MagnificoPonto.Models;

namespace MagnificoPonto.Controllers
{
    public class ContatosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContatosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Contatos
        public async Task<IActionResult> Mensagens()
        {
              return View(await _context.Contatos.ToListAsync());
        }

        // GET: Contatos/Details/5
        public async Task<IActionResult> Visualizar(int? id)
        {
            if (id == null || _context.Contatos == null)
            {
                return NotFound();
            }

            var contatoModel = await _context.Contatos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contatoModel == null)
            {
                return NotFound();
            }

            return View(contatoModel);
        }

        // GET: Contatos/Create
        public IActionResult Enviar()
        {
            return View();
        }

        // POST: Contatos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Enviar([Bind("Id,Nome,Email,Assunto,Mensagem,CriadoEm")] ContatoModel contatoModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contatoModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Enviar));
            }
            return View(contatoModel);
        }


        

        // GET: Contatos/Delete/5
        public async Task<IActionResult> Apagar(int? id)
        {
            if (id == null || _context.Contatos == null)
            {
                return NotFound();
            }

            var contatoModel = await _context.Contatos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contatoModel == null)
            {
                return NotFound();
            }

            return View(contatoModel);
        }

        // POST: Contatos/Delete/5
        [HttpPost, ActionName("Apagar")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ApagarConfirmed(int id)
        {
            if (_context.Contatos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Contatos'  is null.");
            }
            var contatoModel = await _context.Contatos.FindAsync(id);
            if (contatoModel != null)
            {
                _context.Contatos.Remove(contatoModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Mensagens));
        }

        private bool ContatoModelExists(int id)
        {
          return _context.Contatos.Any(e => e.Id == id);
        }
    }
}

codigo-fonte/MagnificoPonto/MagnificoPonto/Controllers/ListarProdutosController.cs
using MagnificoPonto.Data;
using MagnificoPonto.Models;
using MagnificoPonto.Services;
using MagnificoPonto.Services.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace MagnificoPonto.Controllers
{
    public class ListarProdutosController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ListarProdutosController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> ListaProdutos()
        {
            var listarProdutos = await _context.Produtos.ToListAsync();
            return View(listarProdutos);
        }

        // GET: Produtos/Details/5
        public async Task<IActionResult> InfoProdutos(int? id)
        {

            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produtoModel = await _context.Produtos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produtoModel == null)
            {
                return NotFound();
            }

            return View(produtoModel);
        }
    }
}

codigo-fonte/MagnificoPonto/MagnificoPonto/Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MagnificoPonto.Data;
using MagnificoPonto.Models;
using System.Reflection;

namespace MagnificoPonto.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private string caminhoServidor;

        public ProdutosController(ApplicationDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            caminhoServidor = environment.WebRootPath;
        }

        // GET: Produtos
        public async Task<IActionResult> Index()
        {
              return View(await _context.Produtos.ToListAsync());
        }

        // GET: Produtos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produtoModel = await _context.Produtos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produtoModel == null)
            {
                return NotFound();
            }

            return View(produtoModel);
        }

        // GET: Produtos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produtos/Create        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProdutoModel produtoModel, IFormFile foto)
        {
            string caminhoParaSalvarImagem = caminhoServidor + "\\Amigurumis\\";
            string novoNomeParaImagem = Guid.NewGuid().ToString() + "_" + foto.FileName;

            if (!Directory.Exists(caminhoParaSalvarImagem))
            {
                Directory.CreateDirectory(caminhoParaSalvarImagem);
            }

            using (var stream = System.IO.File.Create(caminhoParaSalvarImagem + novoNomeParaImagem))
            {
                foto.CopyTo(stream);
            }

            produtoModel.ImageFileName = novoNomeParaImagem;

            if (ModelState.IsValid)
            {
                _context.Add(produtoModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produtoModel);
        }

        // GET: Produtos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produtoModel = await _context.Produtos.FindAsync(id);
            if (produtoModel == null)
            {
                return NotFound();
            }
            return View(produtoModel);
        }

        // POST: Produtos/Edit/5        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProdutoModel produtoModel, IFormFile foto)
        {
            if (id != produtoModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                string caminhoParaSalvarImagem = caminhoServidor + "\\Amigurumis\\";
                string novoNomeParaImagem = Guid.NewGuid().ToString() + "_" + foto.FileName;

                if (!Directory.Exists(caminhoParaSalvarImagem))
                {
                    Directory.CreateDirectory(caminhoParaSalvarImagem);
                }

                using (var stream = System.IO.File.Create(caminhoParaSalvarImagem + novoNomeParaImagem))
                {
                    foto.CopyTo(stream);
                }

                produtoModel.ImageFileName = novoNomeParaImagem;

                try
                {
                    _context.Update(produtoModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutoModelExists(produtoModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produtoModel);
        }

        // GET: Produtos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Produtos == null)
            {
                return NotFound();
            }

            var produtoModel = await _context.Produtos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produtoModel == null)
            {
                return NotFound();
            }

            return View(produtoModel);
        }

        // POST: Produtos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Produtos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Produtos'  is null.");
            }
            var produtoModel = await _context.Produtos.FindAsync(id);
            if (produtoModel != null)
            {
                _context.Produtos.Remove(produtoModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutoModelExists(int id)
        {
          return _context.Produtos.Any(e => e.Id == id);
        }

       

    }
}

codigo-fonte/MagnificoPonto/MagnificoPonto/Controllers/ShoppingCartController.cs
using MagnificoPonto.Data;
using MagnificoPonto.Models;
using MagnificoPonto.Services.Models;
using MagnificoPonto.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace MagnificoPonto.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShoppingCartController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ShoppingCart
        public async Task<IActionResult> Index()
        {
            var shoppingCartId = HttpContext.Session.GetInt32("ShoppingCartId");

            if (shoppingCartId == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.ShoppingCarts
                .Include(s => s.CartItems)
                .ThenInclude(c => c.Product)
                .FirstOrDefaultAsync(s => s.ShoppingCartId == shoppingCartId);

            if (shoppingCart == null)
            {
                return NotFound();
            }

            if (HttpContext.Session.GetInt32("FormularioEntregaId") != null){
                var formularioEntrega = await _context.FormularioEntregas.FirstOrDefaultAsync(s => s.Id == HttpContext.Session.GetInt32("FormularioEntregaId"));
                List<int> productIds = shoppingCart.CartItems.Select(c => c.Product.Id).ToList();

                List<ProdutoModel> models = await _context.Produtos
                    .Where(m => productIds.Contains(m.Id))
                    .ToListAsync();

                if (!models.Any())
                {
                    NotFound();
                }

                var result = await MelhorEnvioService.GetApiResponse(models, formularioEntrega.Cep.ToString());
                List<MelhorEnvioResponse> rootList = JsonConvert.DeserializeObject<List<MelhorEnvioResponse>>(result.Content);
                List<Dictionary<string, string>> keyValuePairs = new List<Dictionary<string, string>>();
                foreach (var item in rootList)
                {
                    var dict = new Dictionary<string, string>
                    {
                        { "Serviço", item.name },
                        { "Preço", item.price != null ? item.price : "" }
                    };
                    keyValuePairs.Add(dict);
                }

                ViewBag.Result = keyValuePairs;
            }
            
            return View(shoppingCart);
        }

        // POST: ShoppingCart/AddToCart/5
        [HttpPost]
        public async Task<IActionResult> AddToCart(int productId, string description)
        {
            var shoppingCartId = HttpContext.Session.GetInt32("ShoppingCartId");
            
            var product = await _context.Produtos.FindAsync(productId);
            if (product == null)
            {
                return NotFound();
            }

            var cartItem = new CartItem { Product = product, Quantity = 1, Description = description };
            ShoppingCart shoppingCart;
            if (shoppingCartId == null) 
            { 
                shoppingCart = new ShoppingCart(); 
                shoppingCart.CartItems = new List<CartItem>
                    {
                        cartItem
                    };
                _context.Add(shoppingCart);
            }
            else
            {
                shoppingCart = await _context.ShoppingCarts
                .Include(s => s.CartItems)
                .ThenInclude(c => c.Product)
                .FirstOrDefaultAsync(s => s.ShoppingCartId == shoppingCartId);

                cartItem.ShoppingCart = shoppingCart;
                _context.Add(cartItem);
            }

            
            await _context.SaveChangesAsync();

            HttpContext.Session.SetInt32("ShoppingCartId", shoppingCart.ShoppingCartId);

            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int cartItemId)
        {
            var shoppingCartId = HttpContext.Session.GetInt32("ShoppingCartId");

            var shoppingCart = await _context.ShoppingCarts.Include(s => s.CartItems).FirstOrDefaultAsync(s => s.ShoppingCartId == shoppingCartId);

            if (shoppingCart == null)
            {
                return NotFound();
            }

            var cartItem = shoppingCart.CartItems.Find(s => s.CartItemId == cartItemId);

            shoppingCart.CartItems.Remove(cartItem);

            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

codigo-fonte/MagnificoPonto/MagnificoPonto/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MagnificoPonto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MagnificoPonto.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.0.6/datatables.min.css" rel="stylesheet">
</head>

<body>
    <header>

        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <strong><span>Magnífico</span> Ponto</strong>
                </a>

                <div class="d-lg-none">  
                    <a class="bi bi-cart2 custom-icon m-3" asp-controller="ShoppingCart" asp-action="Index"></a>
                    <a class="bi-person custom-icon me-3" asp-area="Identity" asp-page="/Account/Register"></a>
                    <a class="bi bi-door-open custom-icon me-2" asp-area="Identity" asp-page="/Account/Login"></a>
                </div>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Sobre">Sobre</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="VendaProdutos" asp-action="ListaProdutos">Produtos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="FAQs">FAQs</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Contatos" asp-action="Enviar">Contato</a>
                        </li>

                        @if (User.Identity.IsAuthenticated && UserManager.GetUserAsync(User).Result.Email == "adminmagponto@gmail.com")
                        {
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Produtos" asp-action="Index">Amigurumis</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Contatos" asp-action="Mensagens">Mensagens</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="RelatorioVendas" asp-action="Index">Relatório</a>
                            </li>
                        }
                        
                    </ul>                    

                    <partial name="_LoginPartial" />
                    
                </div>
            </div>
        </nav>


    </header>
    <div class="container mt-3">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>




    <footer class="site-footer">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-10 me-auto mb-4">
                    <h4 class="text-white mb-3"><a asp-controller="Home" asp-action="Index">Magnífico</a> Ponto</h4>
                    <p class="copyright-text text-muted mt-lg-5 mb-4 mb-lg-0">Copyright © 2024 <strong>Magnífico Ponto</strong></p>
                    <br>
                 @* <p class="copyright-text">Desenvolvido por <a href="#" target="_blank">Equipe</a></p> *@
                </div>

                <div class="col-lg-5 col-8">
                    <h5 class="text-white mb-3">Mapa do site</h5>

                    <ul class="footer-menu d-flex flex-wrap">
                        <li class="footer-menu-item"><a class="footer-menu-link" asp-controller="Home" asp-action="Index">Início</a></li>

                        <li class="footer-menu-item"><a class="footer-menu-link" asp-controller="Home" asp-action="Sobre">Sobre</a></li>

                        <li class="footer-menu-item"><a class="footer-menu-link" asp-controller="ListarProdutos" asp-action="ListaProdutos">Produtos</a></li>

                        <li class="footer-menu-item"><a class="footer-menu-link" asp-controller="Home" asp-action="FAQs">FAQs</a></li>

                        <li class="footer-menu-item"><a class="footer-menu-link" asp-controller="Contatos" asp-action="Enviar">Contato</a></li>

                        <li class="footer-menu-item"><a class="footer-menu-link" asp-controller="Home" asp-action="Termos">Termos de uso</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-4">
                    <h5 class="text-white mb-3">Social</h5>

                    <ul class="social-icon ">
                        <li><a href="https://api.whatsapp.com/send/?phone=5531987259104&text&type=phone_number&app_absent=0" target="_blank" class="social-icon-link bi-whatsapp"></a></li>
                        <li><a href="https://www.instagram.com/magnifico.ponto/?ref=AIRDOLPHIN" target="_blank" class="social-icon-link bi-instagram"></a></li>
                    </ul>
                </div>

            </div>
        </div>
    </footer>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.0.6/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>