MagnificoPonto/MagnificoPonto/Areas/Admin/Controllers/AdminGraficoController.cs
using MagnificoPonto.Areas.Admin.Services;
using Microsoft.AspNetCore.Mvc;

namespace MagnificoPonto.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminGraficoController : Controller
    {
        private readonly GraficosVendasService _graficoVendas;

        public AdminGraficoController(GraficosVendasService graficoVendas)
        {
            _graficoVendas = graficoVendas ?? throw new ArgumentNullException(nameof(graficoVendas));
        }

        public JsonResult VendasAmigurumis(int dias)
        {
            var amigurumisVendasTotais = _graficoVendas.GetVendasAmigurumis(dias);
            return Json(amigurumisVendasTotais);
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult VendasMensal()
        {
            return View();
        }

        [HttpGet]
        public IActionResult VendasSemanal()
        {
            return View();
        }
    }
}

MagnificoPonto/MagnificoPonto/Areas/Admin/Views/AdminGrafico/Index.cshtml
<title>
    @ViewData["Title"] - Gráfico de Vendas
</title>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">
    google.charts.load('current', { 'packages': ['corechart', 'bar'] });

    google.charts.setOnLoadCallback(CarregaDados);

    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("VendasAmigurumis", "AdminGrafico")',
            data: { dias: 360 },
            dataType: "json",
            type: "GET",
            error: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toast.error(err.message);
            },
            success: function (data) {
                GraficoVendasAmigurumis(data);
                return false;
            }
        });
    }
        function GraficoVendasAmigurumis(data) {
            var dataArray = [
                ['Amigurumi', 'Quantidade', 'Valores(R$)']
            ];
            $.each(data, function (i, item) {
                dataArray.push([item.amigurumiNome, item.amigrumisQuantidade, item.amigurumisValorTotal]);
            });

            var data = google.visualization.arrayToDataTable(dataArray);

            var options = {
                title: 'Amigurumis - Vendas nos últimos 360 dias',
                chartArea: {
                    width: '70%'
                },
                colors: ['#5202b5', '#d2a828'],
                hAxis: {
                    title: 'Valor Total (em Reais)',
                    minValue: 0
                },
                vAxis: {
                    title: 'Amigurumis'
                }
            };
            var chart = new google.visualization.BarChart(document.getElementById('chart_div'));

            chart.draw(data, options);

        }
</script>

MagnificoPonto/MagnificoPonto/Areas/Admin/Views/AdminGrafico/VendasMensal.cshtml
<title>
    @ViewData["Title"] - Gráfico de Vendas
</title>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">
    google.charts.load('current', { 'packages': ['corechart', 'bar'] });

    google.charts.setOnLoadCallback(CarregaDados);

    //obter dados
    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("VendasAmigurumis", "AdminGrafico")',
            data: { dias: 30 },
            dataType: "json",
            type: "GET",
            error: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toast.error(err.message);
            },
            success: function (data) {
                GraficoVendasAmigurumis(data);
                return false;
            }
        });

        function GraficoVendasAmigurumis(data) {
            var dataArray = [
                ['Amigurumi', 'Quantidade', 'Valores(R$)']
            ];
            $.each(data, function (i, item) {
                dataArray.push([item.amigurumiNome, item.amigrumisQuantidade, item.amigurumisValorTotal]);
            });

            var data = google.visualization.arrayToDataTable(dataArray);

            var options = {
                title: 'Amigurumis - Vendas nos últimos 30 dias',
                animation: {
                    duration: 3000,
                    easing: 'out',
                    startup: true
                },
                chartArea: {
                    width: '70%'
                },
                colors: ['#5202b5', '#d2a828'],
                hAxis: {
                    title: 'Valor Total (em Reais)',
                    minValue: 0
                },
                vAxis: {
                    title: 'Amigurumis'
                }
            };

            //prepara a visualização e defino o tipo de gráfico e o local
            var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));

            chart.draw(data, options);

        }
    }
</script>

MagnificoPonto/MagnificoPonto/Areas/Admin/Views/AdminGrafico/VendasSemanal.cshtml
<title>
    @ViewData["Title"] - Gráfico de Vendas
</title>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">
    google.charts.load('current', { 'packages': ['corechart', 'bar'] });

    google.charts.setOnLoadCallback(CarregaDados);

    //obter dados
    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("VendasAmigurumis", "AdminGrafico")',
            data: { dias: 7 },
            dataType: "json",
            type: "GET",
            error: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toast.error(err.message);
            },
            success: function (data) {
                GraficoVendasAmigurumis(data);
                return false;
            }
        });
    }
        return false

    //prepara os dados obtidos
    function GraficoVendasAmigurumis(data) {
        var dataArray = [
            ['Amigurumi', 'Quantidade', 'Valores(R$)']
        ];
        $.each(data, function (i, item) {
            dataArray.push([item.amigurumiNome, item.amigrumisQuantidade, item.amigurumisValorTotal]);
        });

        var data = google.visualization.arrayToDataTable(dataArray);

        var options = {
            title: 'Amigurumis - Vendas nos últimos 7 dias',
            curveType: 'function',
            legend: { position : 'bottom' },
            chartArea: {
                width: '70%'
            },
            colors: ['#5202b5', '#d2a828'],
            hAxis: {
                title: 'Valor Total (em Reais)',
                minValue: 0
            },
            vAxis: {
                title: 'Amigurumis'
            }
        };

        //prepara a visualização e defino o tipo de gráfico e o local
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

        chart.draw(data, options);
    }
</script>